title: ESMARConf2025
preposition: at
description: >-
  June 11th - 13th 2025
baseurl: "/ESMARConf2025" # the subpath of your site, e.g. /blog
url: "https://eshackathon.org" # the base hostname & protocol for your site, e.g. https://example.com

remote_theme: "DigitaleGesellschaft/jekyll-theme-conference@v3.6.1"

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Timezone
  tz: "+01:00"

  # Show theme errors:
  show_errors: False

  # Navigation bar
  navigation:
    logo:
      name: ESMARConf
      img: 'logo-icon-64.png'
      url: 'https://esmarconf.org/'
    breakpoint: md
    links:
      - name: Submit an Abstract
        relative_url: /submit/
      - name: Register
        absolute_url: https://opencollective.com/esmarconf/events/esmarconf2025-9e367c01
      - name: Apply for a Bursary
        relative_url: /bursary/
      - name: Programme
        relative_url: /programme/
      #- name: Talks
      #  relative_url: /talks/
      #- name: Speakers
      #  relative_url: /speakers/
      #- name: Location
      #  relative_url: /location/
      #- name: Previous Editions
      #  menu:
      #    - name: 2020 (current)
      #      disabled: true
      #    - name: 2019
      #      relative_url: /2019/
      #    - name: 2018
      #      relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'ESMARConf2025.png'      # inside /assets/images/
      open_graph: 'ESMARConf2025.png'  # inside /assets/images/

  # Main landing page
  main:
    #logo:
    #  img: 'ESMARConf2025.png'
    links:
      - name: Submit an Abstract
        relative_url: /submit/
      - name: Apply for a Bursary
        relative_url: /bursary/
      - name: Programme
        relative_url: /programme/
      - live: true
      - name: Location
        relative_url: /location/
        disabled: true
      - name: Register
        disabled: false
        absolute_url: https://opencollective.com/esmarconf/events/esmarconf2025-9e367c01
        # absolute_url: ''

  # Information boxes
  info_bars:
    - title: Latest News
      color: primary
      main_only: true
      text: |
        Bursaries and registration is now open for ESMARConf2025!
    #- text: This is just some random content for demonstration purposes.
    #  color: warning
    #  pages_only: true

  # Live indications
  live:
    # date: 01.01.2020
    # timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Keynote
        color: primary
      - name: Tutorial
        color: dark
      - name: Talk
        color: secondary
      - name: Workshop
        color: info
      - name: Panel Discussion
        color: danger
      - name: Live
        color: success
      - name: Break
        color: light

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    #map:
    #  # Initial map center point
    #  home_coord: 47.37808, 8.53935
    #  # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
    #  # The following do match the Bootstrap design not too badly:
    #  #   - Thunderforest.Neighbourhood
    #  #   - Esri.WorldTopoMap
    #  map_provider: "OpenStreetMap.Mapnik"
    #  default_zoom: 17


  program:
    # URL of program page
    url: '/programme'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
